<#
.SYNOPSIS
    Register a `symbion` PowerShell function so the launcher works from any directory.

.DESCRIPTION
    By default Symbion can only be invoked from the repo root (.\symbion.ps1).
    This script writes a small function into your PowerShell profile that calls
    the launcher at this repo's location, so typing `symbion` from anywhere
    runs `<this-repo>\symbion.ps1` with passthrough args.

    Idempotent: re-running replaces the previous block instead of stacking.
    Per-machine: the registered function hard-codes THIS clone's path, so
    on a different machine you re-run install-cli.ps1 from that clone and
    the function points wherever that clone lives. This is what preserves
    plug-and-play across machines without committing absolute paths to git.

    Writes to $PROFILE.CurrentUserAllHosts so both Windows PowerShell 5.1
    and PowerShell 7+ pick it up.

.PARAMETER Uninstall
    Remove the symbion-cli block from the profile instead of installing.

.EXAMPLE
    .\scripts\install-cli.ps1
    Installs/updates the function. Open a new PowerShell window and run `symbion`.

.EXAMPLE
    .\scripts\install-cli.ps1 -Uninstall
    Removes the function. Existing shells keep it until they restart.
#>
[CmdletBinding()]
param(
    [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'

# Repo root = parent of scripts/. Launcher lives at <repo>\symbion.ps1.
$RepoRoot = Split-Path -Parent $PSScriptRoot
$Launcher = Join-Path $RepoRoot 'symbion.ps1'

if (-not (Test-Path -LiteralPath $Launcher)) {
    Write-Error "Launcher not found at $Launcher. Run install-cli.ps1 from inside a Symbion clone."
    exit 1
}

$ProfilePath = $PROFILE.CurrentUserAllHosts
$BeginMarker = '# >>> symbion-cli >>>'
$EndMarker   = '# <<< symbion-cli <<<'

# Profile parent dir might not exist yet (fresh user, OneDrive Documents path).
$ProfileDir = Split-Path -Parent $ProfilePath
if (-not (Test-Path -LiteralPath $ProfileDir)) {
    New-Item -ItemType Directory -Path $ProfileDir -Force | Out-Null
}

# Read existing profile (empty if missing). Strip any prior symbion-cli block
# so reinstall is clean and uninstall has something to find.
$existing = if (Test-Path -LiteralPath $ProfilePath) {
    Get-Content -LiteralPath $ProfilePath -Raw
} else {
    ''
}

# Multiline regex eats the markers + everything between, plus the trailing
# newline so we don't leave a blank gap on uninstall/reinstall.
$pattern = "(?ms)^\s*$([regex]::Escape($BeginMarker)).*?$([regex]::Escape($EndMarker))\s*\r?\n?"
$stripped = [regex]::Replace($existing, $pattern, '')

if ($Uninstall) {
    if ($stripped -eq $existing) {
        Write-Host "No symbion-cli block found in $ProfilePath. Nothing to remove."
        exit 0
    }
    # If the file is now empty (we created it just for our block), delete it.
    if ([string]::IsNullOrWhiteSpace($stripped)) {
        Remove-Item -LiteralPath $ProfilePath -Force
        Write-Host "Removed symbion-cli block and deleted empty profile: $ProfilePath"
    } else {
        Set-Content -LiteralPath $ProfilePath -Value $stripped -Encoding UTF8 -NoNewline
        Write-Host "Removed symbion-cli block from $ProfilePath"
    }
    Write-Host "Open a new PowerShell window for the change to take effect."
    exit 0
}

# Build the new block. Single-quoted here-string so $args and the path stay
# literal in the profile (no interpolation at write time).
$LauncherEscaped = $Launcher.Replace("'", "''")
$block = @"
$BeginMarker
# Auto-generated by symbion\scripts\install-cli.ps1. Re-run that script to update,
# or pass -Uninstall to remove. Manual edits below the markers will be lost.
function symbion {
    & '$LauncherEscaped' @args
}
$EndMarker
"@

# Append the block. Ensure exactly one blank line between any existing
# content and our block so the profile stays readable.
$newContent = if ([string]::IsNullOrWhiteSpace($stripped)) {
    $block + "`r`n"
} else {
    $stripped.TrimEnd() + "`r`n`r`n" + $block + "`r`n"
}

Set-Content -LiteralPath $ProfilePath -Value $newContent -Encoding UTF8 -NoNewline

Write-Host "Installed 'symbion' function in $ProfilePath"
Write-Host "  -> $Launcher"
Write-Host ""
Write-Host "Open a new PowerShell window, then run:  symbion"
Write-Host "(or:  symbion --web)"
